version: '3.8'

services:
  # Servidor Web (Nginx)
  web:
    image: nginx:latest
    container_name: nginx-barbearia
    ports:
      - "3300:80"  # Mapeando a porta 3300 do host para a porta 80 do container
    volumes:
      - ./app/public:/usr/share/nginx/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - barbearia_net

  # Servidor PHP (PHP-FPM)
  php:
    image: php:8.0-fpm
    container_name: php-fpm-barbearia
    volumes:
      - ./app:/var/www/html
    networks:
      - barbearia_net

  # Banco de Dados MySQL
  db:
    image: mysql:5.7
    container_name: mysql-barbearia
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: barbearia
      MYSQL_USER: barbearia_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Script de inicialização
    networks:
      - barbearia_net

networks:
  barbearia_net:
    driver: bridge

volumes:
  db_data:
